# Generated by Django 4.0.3 on 2022-07-08 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvarients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='products',
            name='varients',
        ),
        migrations.AddField(
            model_name='products',
            name='varients',
            field=models.ManyToManyField(to='my_app.productvarients'),
        ),
    ]
