# Generated by Django 4.0.3 on 2022-07-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_productvarients_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarients',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvarients',
            name='updated_at',
        ),
    ]
