# Generated by Django 4.0.3 on 2022-07-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_productvarients_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='varients',
        ),
        migrations.AddField(
            model_name='products',
            name='varients',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.productvarients'),
        ),
    ]
